CREATE TABLE books
(
    id               BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title            VARCHAR(255) NOT NULL,
    author           VARCHAR(255) NOT NULL,
    description      VARCHAR(255) NOT NULL,
    isbn             VARCHAR(255) NOT NULL,
    genre            VARCHAR(255)    NOT NULL
);